/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bukwrap;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.io.*;

/**
 *
 * @author master
 */
public class Bukwrap extends javax.swing.JFrame {

  public double idLength = 0;
  public double idWidth = 0;
  public double idDepth = 0;
  public double odLength = 0;
  public double odWidth = 0;
  public double odDepth = 0;
    
    /**
     * Creates new form BukwrapA
     */
    public Bukwrap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPSflap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMinD = new javax.swing.JTextField();
        txtBuffer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblblksz = new javax.swing.JLabel();
        dimtype = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lsz = new javax.swing.JTextField();
        r2r2upint = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cflute = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        wsz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dsz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFilePathName = new javax.swing.JTextField();
        createDxf = new javax.swing.JButton();
        btnBlkSz = new javax.swing.JButton();
        txtNoBend = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bukwrap");

        txtPSflap.setText("64");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("P and S Flap:");

        txtMinD.setText("12");

        txtBuffer.setText("20.5");
        txtBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBufferActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Min Depth Size:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Buffer:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("File Name:");

        lblblksz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblblksz.setText("1up Blank Size:");

        dimtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID: Internal Dimensions", "BB: Bend to Bend", "OD: Outside Dimensions" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Dim Type:");

        lsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lszActionPerformed(evt);
            }
        });

        r2r2upint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r2r2upint.setText("Interlock:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Pack Size:");

        cflute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E 2mm", "B 3mm", "C 5mm", "D (M, R, S) 2.5mm", "EB 5mm", "F 1mm", "G (N) 0.6mm", "BC 7mm" }));
        cflute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfluteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Flute:");

        jLabel5.setText("x");

        dsz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dszFocusLost(evt);
            }
        });

        jLabel6.setText("x");

        txtFilePathName.setText("aaNewDrawing.dxf");

        createDxf.setText("Create DXF Drawing");
        createDxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDxfActionPerformed(evt);
            }
        });

        btnBlkSz.setText("Calc Blank Size");
        btnBlkSz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlkSzActionPerformed(evt);
            }
        });

        txtNoBend.setText("2");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("No Depth Bends:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblblksz, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNoBend, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(328, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPSflap, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(414, 414, 414))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cflute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(305, 305, 305))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNoBend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPSflap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cflute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(lblblksz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBufferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBufferActionPerformed

    private void lszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lszActionPerformed

    private void dszFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dszFocusLost
    }//GEN-LAST:event_dszFocusLost

    private void createDxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDxfActionPerformed
    double l = Double.parseDouble(lsz.getText());
    double w = Double.parseDouble(wsz.getText());
    double d = Double.parseDouble(dsz.getText());
    double bendno = Double.parseDouble(txtNoBend.getText());
    double mind = Double.parseDouble(txtMinD.getText());
    double buffer = Double.parseDouble(txtBuffer.getText());
    double psflap = Double.parseDouble(txtPSflap.getText());
    
    drawbukwrapcls oDxf = new drawbukwrapcls();
    oDxf.xabs = 0;
    oDxf.yabs = 0;
    getSizes();
    oDxf.length = this.idLength; //Double.parseDouble(lsz.getText());
    oDxf.width = this.idWidth; //Double.parseDouble(wsz.getText());
    oDxf.depth = this.idDepth; // Double.parseDouble(dsz.getText());
    oDxf.dimType = (String) dimtype.getSelectedItem();
    String flute = (String) cflute.getSelectedItem();
    flute = flute.substring(0, 2).trim();
    oDxf.flute = flute;
//    oDxf.findID();
    
    oDxf.mindepth = Double.parseDouble(txtMinD.getText());
    oDxf.noBends = Integer.parseInt(txtNoBend.getText());
    oDxf.buffer = Double.parseDouble(txtBuffer.getText());
    oDxf.psflap = Double.parseDouble(txtPSflap.getText());
    
    String outputDxfData = oDxf.drawbukwrap();
    
    String outputDir = ""; // "../temp/";
    File f = new File(outputDir + txtFilePathName.getText());
    if(f.exists() && !f.isDirectory()) { 
      f.delete();
    }
    String outputDxfFile = outputDir + txtFilePathName.getText(); // "testfilel.dxf"; // "/var/www/temp/testfilel.dxf";
    
    BufferedWriter writer = null; // Note outside try block
    try {
      //create a file
      File newDxfFile = new File(outputDxfFile);
      
      writer = new BufferedWriter(new FileWriter(newDxfFile));
      writer.write(outputDxfData);
      writer.flush();
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      try {
        // Close the writer regardless of what happens...
        writer.close();
      } catch (Exception e) {
      }
    }
    JOptionPane.showMessageDialog(null, "Saved: " + outputDxfFile);

    }//GEN-LAST:event_createDxfActionPerformed

    private void btnBlkSzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlkSzActionPerformed

    double bendno = Double.parseDouble(txtNoBend.getText());
    double mind = Double.parseDouble(txtMinD.getText());
    double buffer = Double.parseDouble(txtBuffer.getText());
    double psflap = Double.parseDouble(txtPSflap.getText());
    
    parcelSizes oBjt = new parcelSizes();
    getSizes();
    oBjt.odLength = this.odLength;
    oBjt.odWidth = this.odWidth;
    oBjt.odDepth = this.odDepth;
    oBjt.checkSizes();
    
    //  JOptionPane.showMessageDialog(null, l + "*W=" + w + "*D=" + d, "Info", JOptionPane.INFORMATION_MESSAGE);
    drawbukwrapcls oDxf = new drawbukwrapcls();
    oDxf.xabs = 0;
    oDxf.yabs = 0;
        
    oDxf.length = this.idLength; //Double.parseDouble(lsz.getText());
    oDxf.width = this.idWidth; //Double.parseDouble(wsz.getText());
    oDxf.depth = this.idDepth; // Double.parseDouble(dsz.getText());
  
    oDxf.dimType = (String) dimtype.getSelectedItem();
    String cFlute = (String) cflute.getSelectedItem();
    oDxf.flute = cFlute.substring(0, 2).trim();;
//    oDxf.findID();
    
    oDxf.mindepth = Double.parseDouble(txtMinD.getText());    
    oDxf.noBends = Integer.parseInt(txtNoBend.getText());
    oDxf.buffer = Double.parseDouble(txtBuffer.getText());
    oDxf.psflap = Double.parseDouble(txtPSflap.getText());
    
    oDxf.calcBlkSz();
    lblblksz.setText("Blank Size: " + String.valueOf(oDxf.s1way) + " x " + String.valueOf(oDxf.n2way));

    }//GEN-LAST:event_btnBlkSzActionPerformed
// btnBlkSzActionPerformed
    
    
    private void cfluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfluteActionPerformed
        // TODO add your handling code here:
        String flute = (String) cflute.getSelectedItem();
        flute = flute.substring(0, 2).trim();
        if(flute.equals("E") || flute.equals("F") || flute.equals("G")) {
        txtBuffer.setText("20.5");
      } else {
        txtBuffer.setText("30");
      } // end of if-else
    }//GEN-LAST:event_cfluteActionPerformed

    
    
public void getSizes() {
    this.idLength = Double.parseDouble(lsz.getText());
    this.idWidth = Double.parseDouble(wsz.getText());
    this.idDepth = Double.parseDouble(dsz.getText());
    String cFlute = (String) cflute.getSelectedItem();
    cFlute = cFlute.substring(0, 2).trim();
 
    // Get Inside Size
    if (dimtype.getSelectedItem() == "ID: Internal Dimensions") {
      // Do nothing     
    } else if (dimtype.getSelectedItem() == "OD: Outside Dimensions") { // O/D includes the Buffers
      if (cFlute.equals("B")) {
        this.idLength = this.idLength - ((Double.parseDouble(txtBuffer.getText()) * 2) + 3);
        this.idWidth = this.idWidth - 6;
        this.idDepth = this.idDepth - 11;
      } else if (cFlute.equals("C")) {
        this.idLength = this.idLength - ((Double.parseDouble(txtBuffer.getText()) * 2) + 5);
        this.idWidth = this.idWidth - 9;
        this.idDepth = this.idDepth - 18;       
      } else {  // E flute
        this.idLength = this.idLength - ((Double.parseDouble(txtBuffer.getText()) * 2) + 2);
        this.idWidth = this.idWidth - 4;
        this.idDepth = this.idDepth - 6;
      } // OD
    } else { // Bend to Bend
        if (cFlute == "B") {
          this.idLength = this.idLength - 3;
          this.idWidth = this.idWidth - 3;
          this.idDepth = this.idDepth - 3;          
        } else if (cFlute == "C") {
          this.idLength = this.idLength - 5;
          this.idWidth = this.idWidth - 5;
          this.idDepth = this.idDepth - 5;          
        } else { // E flute
        this.idLength = this.idLength - 2;
        this.idWidth = this.idWidth - 2;
        this.idDepth = this.idDepth - 2;
        }
    } // BtoB
    
    // Set Outside Size
    if (cFlute.equals("B")) {
        this.odLength = this.idLength + ((Double.parseDouble(txtBuffer.getText()) * 2) + 3);
        this.odWidth = this.idWidth + 6;
        this.odDepth = this.idDepth + 11;       
    } else if (cFlute.equals("C")) {
        this.odLength = this.idLength + ((Double.parseDouble(txtBuffer.getText()) * 2) + 5);
        this.odWidth = this.idWidth + 9;
        this.odDepth = this.idDepth + 18;       
    } else {  // E flute
        this.odLength = this.idLength + ((Double.parseDouble(txtBuffer.getText()) * 2) + 2);
        this.odWidth = this.idWidth + 4;
        this.odDepth = this.idDepth + 6;
    }      
  } // getSizes
  

  
  // end methods
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bukwrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bukwrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bukwrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bukwrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bukwrap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlkSz;
    private javax.swing.JComboBox<String> cflute;
    private javax.swing.JButton createDxf;
    private javax.swing.JComboBox<String> dimtype;
    private javax.swing.JTextField dsz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblblksz;
    private javax.swing.JTextField lsz;
    private javax.swing.JLabel r2r2upint;
    private javax.swing.JTextField txtBuffer;
    private javax.swing.JTextField txtFilePathName;
    private javax.swing.JTextField txtMinD;
    private javax.swing.JTextField txtNoBend;
    private javax.swing.JTextField txtPSflap;
    private javax.swing.JTextField wsz;
    // End of variables declaration//GEN-END:variables
}
